"
""Клас Employee моделює працівника із базовими характеристиками:
- lastName — прізвище працівника;
- experienceYears — кількість років досвіду (стаж);
- hourlyRate — ставка оплати за годину роботи;
- minWeeklyHours — мінімальна кількість годин, які працівник має відпрацювати за тиждень.""
"
Class {
	#name : 'Employee',
	#superclass : 'Object',
	#instVars : [
		'lastName',
		'experienceYears',
		'hourlyRate',
		'minWeeklyHours'
	],
	#category : 'StrongWave',
	#package : 'StrongWave'
}
